### ISSUE TITLE
An advice for Teensy ADC part 

### ISSUE THREAD

**Issue by siriulx** [siriulx/GA2#1]
Teensy 3.1 has two ADC, so we can deal with two inputs in a same interrupt.

The library information link: 
https://forum.pjrc.com/threads/25532-ADC-library-update-now-with-support-for-Teensy-3-1

The library project link: 
https://github.com/pedvide/ADC

A example using ADC library: https://github.com/pedvide/ADC/blob/master/examples/analogRead/analogRead.ino

I think 1 kHz sampling rate and 1024 points FFT size may not much accurate. we'd better use 8 kHz and 2048 points, and we sample 2048 points at 8 kHz only need 256 ms.

For memory part, we can only sample two inputs and do the FFT to get two frequencies at one time, and  then redo this part for the rest 4 inputs. Finally, we use the 6 frequencies to drive the 6 servos. microSD is quite slow to read and write.

**Comment by cbarrin** [comment]
Using 8 kHz and 2048 FFT would be less accurate. You would only have a resolution of about 4 Hz whereas with 1 kHz and 1024 FFT you get around a 1 Hz resolution. 

And is there a big benefit to use the second ADC? I saw a project earlier in the semester that used it but I can't remember what it was used for.

**Comment by siriulx** [comment]
I think there will be a problem using 1 kHz sampling rate. The frequency of a guitar is about from 65 to 988 Hz, and using 1kHz sample rate to sample a high frequency sound may not get enough points to represent the changing of the wave.

Using double ADC can save the converting time. We also can use DMA instead of interrupt to become more faster.

**Comment by cbarrin** [comment]
Even then we should only need 2 kHz sampling rate because the Nyquist rate for alias-free sampling is half of the sampling rate. But besides that, Travis and I found our maximum to be about 375 - 400 Hz on the 6th string.

**Comment by siriulx** [comment]
Good, 1 kHz sample rate should be the best. And I'm trying to change the FFT function to reduce memory usage.  Like changing CFFT to RFFT or using Q15 fix-point FFT directly. If success, we will only cost 24kb memory to save these 6 strings data.

**Comment by cbarrin** [comment]
At this point I think Greg is already planning on building the automatic strummer to strum 3 strings. On top of that we haven't really figured out a good way to isolate the peaks of each string and reduce bleeding over of signals. I think one thing that would be really helpful would be to try and find ways to reduce the sampling time. 

Let me know if you have any success with changing the FFT.

**Comment by siriulx** [comment]
Using following code will save a lots of space, but I haven't tested these with real data.

![image](https://cloud.githubusercontent.com/assets/6583339/6753661/156c139a-ceee-11e4-9ad5-49f0314a19e2.png)
**Input and Output Formats for Q15 RFFT**

Declare variables:
uint16_t samples[FFT_SIZE];
uint16_t magnitudes[FFT_SIZE];

In function:
  arm_rfft_instance_q15 fft_inst_r;
  arm_cfft_radix4_instance_q15 fft_inst_c;
  arm_rfft_init_q15(&fft_inst_r, &fft_inst_c, FFT_SIZE, 0, 1);
  arm_rfft_q15(&fft_inst_r, (q15_t *)samples, (q15_t *)magnitudes);

**Comment by siriulx** [comment]
I found another HPS code:
http://stackoverflow.com/questions/19765486/matlab-code-for-harmonic-product-spectrum
And there is a piece of code trying to fix octave error.
I'm not sure if this is the problem we have.
